import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import "./layout.css";
import { Header } from "./_components/header";

const geistSans = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="h-full">
      <body
      // layout-gradient
        className={`${geistSans.className} 
        bg-background
        min-h-screen flex flex-col justify-center items-center w-full  antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
